#
# ██████╗░██████╗░░█████╗░███████╗██╗░██████╗ ░█████╗░██████╗░██████╗░░█████╗░███╗░░██╗░██████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝╚█║██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██╔══██╗████╗░██║██╔════╝
# ██████╔╝██████╔╝███████║█████╗░░░╚╝╚█████╗░ ███████║██║░░██║██║░░██║██║░░██║██╔██╗██║╚█████╗░
# ██╔═══╝░██╔══██╗██╔══██║██╔══╝░░░░░░╚═══██╗ ██╔══██║██║░░██║██║░░██║██║░░██║██║╚████║░╚═══██╗
# ██║░░░░░██║░░██║██║░░██║███████╗░░░██████╔╝ ██║░░██║██████╔╝██████╔╝╚█████╔╝██║░╚███║██████╔╝
# ╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝░░░╚═════╝░ ╚═╝░░╚═╝╚═════╝░╚═════╝░░╚════╝░╚═╝░░╚══╝╚═════╝░
#

# Pipebomb Settings
enable-pipebombs: false
destroys-environment: false
pipebombs-spawn-fire: false
explosion-power-per-bomb: 0.5
max-explosion-power: 20

# Joke book Settings
enable-joke-book: false
joke-book-sound: "prae.danielsmp.jokebook"